"""Beads is authoritative; Markdown views are reproducible exports."""

import hashlib
import json
import re
from pathlib import Path

from .common import WorkflowError, local_dir, lock, run, write_json, write_text


def call(root: Path, *args: str):
    return json.loads(run(root, ["bd", *args, "--json"]))


def issues(root: Path) -> list[dict]:
    return call(root, "list", "--all", "--limit", "0")


def ready(root: Path) -> list[dict]:
    return call(root, "ready", "--limit", "0")


def backlog_entries(source: str) -> list[dict]:
    section = "Backlog"
    result = []
    current = None
    for number, line in enumerate(source.splitlines(), 1):
        if line.startswith("## "):
            section = line[3:]
            current = None
        match = re.match(r"^- \[([ xX])\] (.+)$", line)
        if match:
            title = match[2]
            key = hashlib.sha256(f"{section}\n{title}".encode()).hexdigest()[:24]
            current = {
                "title": title,
                "section": section,
                "closed": match[1].lower() == "x",
                "external_ref": f"backlog:{key}",
                "line": number,
                "details": [],
            }
            result.append(current)
        elif current is not None and line.startswith(("  ", "\t")):
            current["details"].append(line)
    return result


def migrate(root: Path) -> dict:
    with lock(root):
        path = root / "TASKS.md"
        text = path.read_text()
        if "<!-- Generated by just ai-task export" in text:
            return {"status": "already_migrated", "tasks": len(issues(root))}
        digest = hashlib.sha256(text.encode()).hexdigest()
        archive = root / ".ai/backlog-source.md"
        if archive.exists() and archive.read_text() != text:
            raise WorkflowError(
                "Backlog changed since migration started; reconcile .ai/backlog-source.md first"
            )
        archive.write_text(text)
        known = {item.get("external_ref"): item for item in issues(root)}
        count = 0
        for entry in backlog_entries(text):
            item = known.get(entry["external_ref"])
            if item is None:
                item = call(
                    root,
                    "create",
                    "--title",
                    entry["title"],
                    "--external-ref",
                    entry["external_ref"],
                    "--description",
                    f"Imported from .ai/backlog-source.md:{entry['line']} ({entry['section']}).\n"
                    + "\n".join(entry["details"]),
                    "--labels",
                    "backlog",
                )
                known[entry["external_ref"]] = item
                count += 1
            if entry["closed"] and item["status"] != "closed":
                call(
                    root,
                    "close",
                    item["id"],
                    "--reason",
                    "Completed in original backlog before migration",
                )
        if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            raise WorkflowError(
                "TASKS.md changed during migration; imported tasks retained, export deferred"
            )
        write_json(
            local_dir(root) / "backlog-migration.json",
            {"source_sha256": digest, "count": len(known)},
        )
        result = export(root)
        result["imported"] = count
        return result


def task_group(row: dict) -> str:
    """Classify sanitized public tasks into mutually exclusive summary groups."""
    labels = {str(label).lower() for label in row.get("labels", [])}
    title = str(row.get("title", "")).lower()
    external_ref = str(row.get("external_ref", ""))
    if (
        external_ref.startswith("garbanzo-report:")
        or "report" in labels
        or title.startswith("production report")
    ):
        return "production_report"
    if external_ref.startswith("finding:") or "finding" in labels or " finding " in f" {title} ":
        return "dependency_finding"
    if "(in progress)" in title or row.get("status") == "in_progress":
        return "in_progress"
    return "feature_or_infrastructure"


def summarize(
    rows: list[dict],
    *,
    ready_ids: set[str] | None = None,
    limit: int = 10,
    include_reports: bool = False,
    include_findings: bool = False,
) -> dict:
    if limit < 1:
        raise ValueError("summary limit must be at least 1")

    open_rows = [row for row in rows if row.get("status") in {"open", "in_progress"}]
    by_priority: dict[str, int] = {}
    by_group: dict[str, int] = {}
    for row in open_rows:
        priority = f"P{row.get('priority', 2)}"
        group = task_group(row)
        by_priority[priority] = by_priority.get(priority, 0) + 1
        by_group[group] = by_group.get(group, 0) + 1

    group_order = {
        "in_progress": 0,
        "feature_or_infrastructure": 1,
        "production_report": 2,
        "dependency_finding": 3,
    }
    if ready_ids is None:
        ready_ids = {str(row.get("id")) for row in open_rows}
    candidates = []
    for row in open_rows:
        group = task_group(row)
        if group == "production_report" and not include_reports:
            continue
        if group == "dependency_finding" and not include_findings:
            continue
        if str(row.get("id")) not in ready_ids:
            continue
        candidates.append(row)
    # Stable sorts build the final ordering from least to most significant key.
    candidates.sort(key=lambda row: str(row.get("id", "")))
    candidates.sort(key=lambda row: str(row.get("updated_at", "")), reverse=True)
    candidates.sort(key=lambda row: group_order[task_group(row)])
    candidates.sort(key=lambda row: row.get("priority", 2))
    recommended = [
        {
            key: row[key]
            for key in ("id", "title", "priority", "updated_at", "dependency_count")
            if key in row
        }
        | {"group": task_group(row)}
        for row in candidates[:limit]
    ]
    return {
        "open_total": len(open_rows),
        "blocked_total": sum(
            bool(row.get("dependency_count", 0)) and str(row.get("id")) not in ready_ids
            for row in open_rows
        ),
        "by_priority": dict(sorted(by_priority.items())),
        "by_group": {
            group: by_group.get(group, 0)
            for group in (
                "in_progress",
                "feature_or_infrastructure",
                "production_report",
                "dependency_finding",
            )
        },
        "recommended_tasks": recommended,
    }


def export(root: Path) -> dict:
    rows = sorted(issues(root), key=lambda row: (row.get("priority", 2), row["id"]))
    output = [
        "# Garbanzo AI — Tasks",
        "",
        "<!-- Generated by just ai-task export; edit tasks in Beads. -->",
        "",
        "Original backlog and notes: [.ai/backlog-source.md](.ai/backlog-source.md).",
        "",
    ]
    public = []
    for row in rows:
        # Production adapters create only sanitized titles; raw metadata/notes never enter exports.
        title = row["title"].replace("\n", " ").replace("\r", " ")
        output.append(
            f"- [{'x' if row['status'] == 'closed' else ' '}] **{row['id']}** P{row.get('priority', 2)} [{row['status']}] {title}"
        )
        public.append(
            {
                key: row[key]
                for key in ("id", "title", "status", "priority", "external_ref", "updated_at")
                if key in row
            }
        )
    write_text(root / "TASKS.md", "\n".join(output) + "\n")
    write_text(
        root / ".beads/issues.jsonl",
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in public),
    )
    return {"status": "exported", "tasks": len(rows), "path": "TASKS.md"}


def handle(args):
    if args.action == "migrate":
        return migrate(args.root)
    if args.action == "export":
        with lock(args.root):
            return export(args.root)
    if args.action == "ready":
        return call(args.root, "ready")
    if args.action == "summary":
        return summarize(
            issues(args.root),
            ready_ids={str(row.get("id")) for row in ready(args.root)},
            limit=args.limit,
            include_reports=args.include_reports,
            include_findings=args.include_findings,
        )
    if args.action == "show":
        return call(args.root, "show", args.id)
    if args.action == "create":
        return call(
            args.root,
            "create",
            "--title",
            args.title,
            "--description",
            args.description,
            "--acceptance",
            args.acceptance,
            "--priority",
            str(args.priority),
        )
    if args.action == "update":
        return call(
            args.root,
            "update",
            args.id,
            "--description",
            args.description,
            "--acceptance",
            args.acceptance,
        )
    if args.action in {"close", "reopen"}:
        return call(args.root, args.action, args.id, "--reason", args.reason)
    if args.action == "depend":
        return call(args.root, "dep", "add", args.id, args.depends_on)
    return issues(args.root)


def register(subparsers):
    parser = subparsers.add_parser("task", help="Beads task graph and backlog migration")
    parser.set_defaults(func=handle, action="list")
    actions = parser.add_subparsers(dest="action")
    for name in ("list", "ready", "migrate", "export"):
        actions.add_parser(name)
    summary = actions.add_parser("summary", help="Compact current task recommendation")
    summary.add_argument("--limit", type=int, default=10)
    summary.add_argument("--include-reports", action="store_true")
    summary.add_argument("--include-findings", action="store_true")
    show = actions.add_parser("show")
    show.add_argument("id")
    for name in ("create", "update"):
        edit = actions.add_parser(name)
        edit.add_argument("title" if name == "create" else "id")
        edit.add_argument("--description", required=True)
        edit.add_argument("--acceptance", required=True)
        edit.add_argument("--priority", type=int, choices=range(5), default=2)
    for name in ("close", "reopen"):
        lifecycle = actions.add_parser(name)
        lifecycle.add_argument("id")
        lifecycle.add_argument("--reason", required=True)
    dep = actions.add_parser("depend")
    dep.add_argument("id")
    dep.add_argument("depends_on")
