#!/usr/bin/env bash
set -euo pipefail

umask 077

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO/deploy/.env"
SIGNING_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/garbanzo-ai/signing"
KEYSTORE_PATH="$SIGNING_DIR/garbanzo-ai-release.jks"
KEY_ALIAS="garbanzo-ai"

die() { echo "ERROR: $*" >&2; exit 1; }

[[ -f "$ENV_FILE" ]] || die "deploy/.env is missing"
command -v keytool >/dev/null 2>&1 || die "keytool is required (install Java 17+)"
command -v openssl >/dev/null 2>&1 || die "openssl is required"

if grep -Eq \
    '^ANDROID_(KEYSTORE_PATH|KEYSTORE_ALIAS|KEYSTORE_PASSWORD|KEY_PASSWORD)=.+' \
    "$ENV_FILE"; then
    die "Android signing is already configured in deploy/.env; refusing to overwrite it"
fi
if [[ -e "$KEYSTORE_PATH" ]]; then
    die "keystore already exists at $KEYSTORE_PATH; refusing to overwrite it"
fi

mkdir -p "$SIGNING_DIR"
chmod 700 "$SIGNING_DIR"

ANDROID_KEYSTORE_PASSWORD="$(openssl rand -hex 32)"
ANDROID_KEY_PASSWORD="$(openssl rand -hex 32)"
export ANDROID_KEYSTORE_PASSWORD ANDROID_KEY_PASSWORD

keytool -genkeypair \
    -keystore "$KEYSTORE_PATH" \
    -storetype JKS \
    -storepass:env ANDROID_KEYSTORE_PASSWORD \
    -keypass:env ANDROID_KEY_PASSWORD \
    -alias "$KEY_ALIAS" \
    -keyalg RSA \
    -keysize 4096 \
    -sigalg SHA256withRSA \
    -validity 36500 \
    -dname "CN=Garbanzo AI, O=Garbanzo AI" \
    -noprompt
chmod 600 "$KEYSTORE_PATH"

ENV_FILE_TMP="$(mktemp "$REPO/deploy/.env.signing.XXXXXX")"
grep -Ev \
    '^ANDROID_(KEYSTORE_PATH|KEYSTORE_ALIAS|KEYSTORE_PASSWORD|KEY_PASSWORD)=' \
    "$ENV_FILE" > "$ENV_FILE_TMP"
{
    printf '\n# Android production signing (generated by just deploy-android-signing-setup).\n'
    printf 'ANDROID_KEYSTORE_PATH=%q\n' "$KEYSTORE_PATH"
    printf 'ANDROID_KEYSTORE_ALIAS=%q\n' "$KEY_ALIAS"
    printf 'ANDROID_KEYSTORE_PASSWORD=%q\n' "$ANDROID_KEYSTORE_PASSWORD"
    printf 'ANDROID_KEY_PASSWORD=%q\n' "$ANDROID_KEY_PASSWORD"
} >> "$ENV_FILE_TMP"
chmod 600 "$ENV_FILE_TMP"
mv "$ENV_FILE_TMP" "$ENV_FILE"

echo "Android production signing configured."
echo "  Keystore: $KEYSTORE_PATH"
echo "  Alias:    $KEY_ALIAS"
echo "Back up the keystore and the four ANDROID_* entries from deploy/.env securely."
